#!/bin/sh
set -ev

export UUID=$(cat /proc/sys/kernel/random/uuid)

if [ -z "$MARATHON_APP_ID" ]; then
  echo "Not running in marathon, so I won't compile the config templates!"
  echo "To force compilation of config, set the \$MARATHON_APP_ID config var."
else
  echo "Compiling config for ${SERVER_CONFIG} and ${SECONDARY_CONFIG}"
  /bin/env_parse ${SERVER_CONFIG}.j2
  /bin/env_parse ${SECONDARY_CONFIG}.j2
fi

su socrata -c '/usr/bin/java \
    -Dconfig.file=${SERVER_ROOT}/${SERVER_CONFIG} \
    -cp $SERVER_ARTIFACT \
    com.socrata.pg.store.Main --migrate Migrate \
    com.socrata.soql-server-pg.migrations \
    '

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_ROOT}/${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath=/mnt/mesos/sandbox \
    -jar $SERVER_ARTIFACT
    '
