#!/bin/sh
set -ev

export UUID=$(cat /proc/sys/kernel/random/uuid)

/bin/env_parse ${SERVER_CONFIG}.j2

/bin/env_parse ${SECONDARY_CONFIG}.j2

exec su socrata -c '/usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_ROOT}/${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -jar $SERVER_ARTIFACT
    '
