apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secondary-watcher-pg
  description: |
    A Postgres secondary-watcher application. secondary-watcher-pg is the
    write-side of the Postgres dataset query backend. It maintains a secondary
    store of datasets in a Postgres instance by implementing the Secondary
    interface.
  links:
    - title: "Ops Doc"
      url: "https://socrata.atlassian.net/wiki/spaces/ONCALL/pages/2158985270/OpsDoc+-+SODA+Server+aka+NBE"
    - title: "New Backend (NBE) Crash Course"
      url: "https://tylertech.sharepoint.com/:v:/r/sites/DataInsightsDivision/Shared%20Documents/Engineering/NewBackendCrashCourse.mov?csf=1&web=1&e=2NsXHJ"
    - title: "Secondary interface"
      url: "https://github.com/socrata-platform/data-coordinator/blob/main/coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/Secondary.scala"
    - title: "Event definitions"
      url: "https://github.com/socrata-platform/data-coordinator/blob/main/coordinatorlib/src/main/scala/com/socrata/datacoordinator/secondary/Event.scala"
  annotations:
    github.com/project-slug: 'socrata-platform/soql-postgres-adapter'
    backstage.io/techdocs-entity: system:soql-server-pg
    infrastructure: apps-marathon
spec:
  type: service
  owner: egress
  lifecycle: production
  system: soql-postgres-adapter
